### ISSUE TITLE
т113-s3

### ISSUE THREAD

**Issue by vvpnet** [ua1arn/hftrx#72]
Добрый день. Не подскажите мне по т113 под управлением Linux.
Я хочу к нему подключить wm8782 ADC через i2s, как мне это сделать? Посоветуйте.

**Comment by ua1arn** [comment]
Как видите, проект bare metal - и я не представляю, есть ли возможность в Вашей версии Linux запустить Alsa или что другое...

**Comment by vvpnet** [comment]
Добрый вечер! Да я как раз использую сборку https://github.com/YuzukiHD/Buildroot-YuzukiSBC на плате MQ-Duo. Там есть Alsa. Вообщем мне нужно получать сигналы от АЦП и управлять им, через i2s. Не понимаю как это сделать. 
Я сделал следующие. Добавил в dts файл:
```
wm8782: wm8782 {
        wm8782 = "ti,wm8782";
    };
```
Подключил АЦП (wm8782) выводам i2s (T113).
В ОС вижу следующие:
```
# cat /proc/asound/cards
 0 [audiocodec     ]: audiocodec - audiocodec
                      audiocodec
# cat /proc/asound/pcm
00-00: SUNXI-CODEC 2030000.codec-0 :  : playback 1 : capture 1

# ls -l /dev/snd/
total 0
drwxr-xr-x    2 root     root            60 Jan  1 00:00 by-path
crw-rw----    1 root     audio     116,   4 Jan  1 00:00 controlC0
crw-rw----    1 root     audio     116,   3 Jan  1 00:00 pcmC0D0c
crw-rw----    1 root     audio     116,   2 Jan  1 00:00 pcmC0D0p
crw-rw----    1 root     audio     116,  33 Jan  1 00:00 timer
```

Я вроде понимаю, что этого недостаточно, нужно ещё наверное прописать в dts выводы, к которым я подключил wm8782 или ещё что-то... вообщем застрял на этом этапе, нужен совет.

**Comment by strijar** [comment]
Ну начать надо с того что по i2s вы кодеком не управляете, а получаете и передаете сам звук. А управление идет через i2c/spi. На который и нужно повесить кодек. Вот этот файл изучите - https://github.com/YuzukiHD/Buildroot-YuzukiSBC/blob/master/buildroot/board/allwinner-generic/sun8i-t113/dts/linux/sun8iw20p1-linux.dtsi

**Comment by vvpnet** [comment]
Прелесть АЦП (wm8782) в том, что она не управлется, через i2c/spi. Управление происходит, через MCLK и все остальное управляется через перемички. У меня подключено АЦП к I2S1. Я посмотрел [sun8iw20p1-linux.dtsi](https://github.com/YuzukiHD/Buildroot-YuzukiSBC/blob/master/buildroot/board/allwinner-generic/sun8i-t113/dts/linux/sun8iw20p1-linux.dtsi). Я так понимаю, что у меня daudio1 должен быть настроен как мастер (для проверки АЦП). Далее я потом обращаюсь в системе /dev/snd/ к pcmC0D0p и должен, что-то получить от туда, верно?
